In [1]:
import sklearn as sk
import pandas as pd
import scipy as scp

In [2]:
pro_data=pd.read_csv('processed_data.csv')

In [3]:
pro_data.head()

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,comment,create_time,like,locate,repost,title,tools,...,repost_nor,comment_nor,fuhao,huati1,huati2,biaoqing,cut_words,word_bag,tf_idf,tf_idf_top5
0,0,0,11800,3939,2015-08-17 20:41,3197,无,7019,BBC推送： 7点25分左右泰国曼谷市中心发生大爆炸.... 在市中心旅游景点四面佛附近.....,微博 weibo.com,...,0.059186,0.040136,.... .... ....,NaN,NaN,NaN,BBC 推送 点 25 分 泰国 曼谷 市中心 发生 爆炸 市中心 旅游景点 四面佛 BBC...,"{128: 1, 30817: 1, 27203: 1, 30113: 1, 28457: ...","{128: 0.2460211157908147, 30817: 0.25640687179...","[(19698, 0.7721249224355116), (11646, 0.556527..."
1,1,1,11801,511,2015-08-17 21:38,747,无,1097,BBC推送： 7点25分左右泰国曼谷市中心发生大爆炸.... 在市中心旅游景点四面佛附近.....,微博 weibo.com,...,0.009250,0.005207,.... .... ....,NaN,NaN,NaN,BBC 推送 点 25 分 泰国 曼谷 市中心 发生 爆炸 市中心 旅游景点 四面佛 BBC...,"{128: 1, 30817: 1, 27203: 1, 30113: 1, 28457: ...","{128: 0.2460211157908147, 30817: 0.25640687179...","[(19698, 0.7721249224355116), (11646, 0.556527..."
2,2,2,11802,542,2015-08-17 22:07,2846,无,1328,话说。最近几年来，各种保守老旧的名字已经不能满足英国人了.... 最近英国公布了一份新生儿姓...,微博 weibo.com,...,0.011198,0.005523,.... ... ... ... .......,NaN,NaN,NaN,话 说 保守 老旧 名字 英国人 英国 公布 一份 新生儿 姓名 调查报告 权力 游戏 里 ...,"{33159: 1, 13320: 1, 35614: 1, 4239: 1, 33812:...","{33159: 0.28615602409287144, 13320: 0.09827933...","[(12890, 0.40792660492240995), (30677, 0.35040..."
3,3,3,11803,723,2015-08-17 23:25,4774,无,596,话说，有个妹纸最近做了个实验：【素颜的妹纸，美图前和美图后，约会软件上的男人们都会有怎样的反...,微博 weibo.com,...,0.005026,0.007367,...... ....,【素颜的妹纸，美图前和美图后，约会软件上的男人们都会有怎样的反差？】,NaN,NaN,话 说 有个 妹纸 做 实验 素颜 妹纸 美图 前 美图 约会 软件 男人 反差 数量 整整...,"{7745: 2, 26274: 1, 25957: 1, 1830: 1, 11207: ...","{7745: 0.45234662075692117, 26274: 0.328153092...","[(27028, 0.6770701205480093), (7745, 0.4523466..."
4,4,4,11804,96,2015-08-17 23:59,828,无,244,【体验-伦敦】谁说看电影只能啃爆米花的？号称电影院里伙食最好的Edible Cinema把自...,街边捡来的iPhone 6,...,0.002057,0.000978,NaN,【体验-伦敦】,NaN,NaN,体验 伦敦 说 电影 只能 啃 爆米花 号称 电影院 里 伙食 EdibleCinema 自...,"{35841: 1, 12994: 1, 12939: 1, 32964: 1, 901: ...","{35841: 0.19205563071959297, 12994: 0.06922356...","[(4683, 0.2983892105719972), (31508, 0.2368141..."

In [4]:
pro_data.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'Unnamed: 0.1.1', 'comment',
       'create_time', 'like', 'locate', 'repost', 'title', 'tools', 'like_nor',
       'repost_nor', 'comment_nor', 'fuhao', 'huati1', 'huati2', 'biaoqing',
       'cut_words', 'word_bag', 'tf_idf', 'tf_idf_top5'],
      dtype='object')